#!/usr/bin/env bash
# PolkaVM corpus via codetracer-polkavm-recorder (prebuilt target/debug).
# Blobs: repo's test-programs/rust/flow_test.polkavm + blobs generated by
# corpus-src/polkavm/blobgen (ProgramBlobBuilder, polkavm-common 0.32.0, same as recorder lock).
set -u
S=${FMT_EFF:?set FMT_EFF to the measurement work directory}
R=${WS:?set WS to the workspace root}/codetracer-polkavm-recorder
echo "recorder revision: $(git -C $R rev-parse HEAD)"
BIN=$R/target/debug/codetracer-polkavm-recorder
(cd $S/corpus-src/polkavm/blobgen && CARGO_HOME=$HOME/.cache/codetracer-polkavm-recorder/cargo-home \
  CARGO_TARGET_DIR=$S/cargo-target/polkavm-blobgen cargo run --offline -q -- $S/corpus-src/polkavm/blobs)
OUT=$S/corpus/polkavm; mkdir -p $OUT; cd $S/corpus-src/polkavm
for f in $R/test-programs/rust/flow_test.polkavm $S/corpus-src/polkavm/blobs/*.polkavm; do
  n=$(basename $f .polkavm)
  rm -rf "$OUT/.tmp"; timeout 300 $BIN record -o "$OUT/.tmp" "$f" >"$S/corpus-src/polkavm/$n.log" 2>&1 && mv "$OUT/.tmp/"*.ct "$OUT/$n.ct" || echo "FAIL $n"
done
rm -rf "$OUT/.tmp"
